CREATE USER 'nextcloud'@'10.105.1.11' IDENTIFIED BY 'test';
CREATE DATABASE IF NOT EXISTS nextcloud CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
GRANT ALL PRIVILEGES ON nextcloud.* TO 'nextcloud'@'10.105.1.11';
FLUSH PRIVILEGES;
